name = "Unnamed Pack"
author = "evancyrulik"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69d89890c8ec800f00182182413f34b15898d903711161e2a7c4719c0b2698fe"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
