name = "Unnamed Pack"
author = "evancyrulik"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7a0b2f9a67b258173477b5aca02405b06a93396cd39efa9926495460d952b1a"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
