name = "Unnamed Pack"
author = "evancyrulik"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eec1b201043ad3d84e2100222b0f32d86728540a5d1d215fe2f85fcbbd5931a7"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
